import { useEffect, useState } from "react";
import { ArrowLeft, Save, ShieldCheck } from "lucide-react";
import { fetchSettings, updateSettings, type PactlineSettings } from "@/lib/pactline-api";

export default function Settings() {
  const [settings, setSettings] = useState<PactlineSettings | null>(null);
  const [draft, setDraft] = useState<Partial<PactlineSettings>>({});
  const [status, setStatus] = useState("Loading workspace settings…");
  const [saving, setSaving] = useState(false);
  useEffect(() => { fetchSettings().then((value) => { setSettings(value); setDraft(value); setStatus("Settings synced from Pactline API"); }).catch((error) => setStatus(error instanceof Error ? error.message : "Settings could not be loaded.")); }, []);
  const save = async () => { setSaving(true); try { const value = await updateSettings(draft); setSettings(value); setDraft(value); setStatus("Workspace settings saved"); } catch (error) { setStatus(error instanceof Error ? error.message : "Settings could not be saved."); } finally { setSaving(false); } };
  return <main className="settings-page"><header className="settings-header"><button className="text-button" onClick={() => window.location.assign("/")}><ArrowLeft size={15} /> Back to control center</button><div className="eyebrow"><span className="eyebrow-line" />WORKSPACE SETTINGS</div><h1>Configure the boundary.</h1><p>These settings are persisted by the Pactline backend and used as workspace context for future runs.</p></header><section className="settings-card"><div className="settings-card-head"><div><div className="micro-label">FINANCE OPS</div><h2>Workspace configuration</h2></div><ShieldCheck size={22} /></div><label>Workspace name<input value={draft.workspaceName || ""} onChange={(event) => setDraft({ ...draft, workspaceName: event.target.value })} /></label><label>Description<textarea value={draft.workspaceDescription || ""} onChange={(event) => setDraft({ ...draft, workspaceDescription: event.target.value })} /></label><label>Approved recipient<input value={draft.defaultRecipient || ""} onChange={(event) => setDraft({ ...draft, defaultRecipient: event.target.value })} /></label><div className="settings-grid"><label>Approval mode<select value={draft.approvalMode || "human-in-the-loop"} onChange={(event) => setDraft({ ...draft, approvalMode: event.target.value })}><option value="human-in-the-loop">Human in the loop</option><option value="default-deny">Default deny</option></select></label><label>Retention days<input type="number" min="1" max="3650" value={draft.retentionDays || 90} onChange={(event) => setDraft({ ...draft, retentionDays: Number(event.target.value) })} /></label></div><div className="settings-actions"><span role="status">{status}</span><button className="primary-button" onClick={() => void save()} disabled={saving || !settings}><Save size={15} />{saving ? "Saving…" : "Save settings"}</button></div></section></main>;
}
