import { readFile, writeFile } from "node:fs/promises";

const path = new URL("../client/src/pages/Home.tsx", import.meta.url);
let source = await readFile(path, "utf8");
source = source.replace('import { useMemo, useState } from "react";', 'import { useEffect, useMemo, useState } from "react";\nimport { fetchRunState, startPactlineRun, submitPactlineDecision, type PactlineRun } from "@/lib/pactline-api";');
source = source.replace('  const [runState, setRunState] = useState<"idle" | "running" | "held" | "approved">("held");', '  const [runState, setRunState] = useState<"idle" | "running" | "held" | "approved" | "rejected">("held");\n  const [liveRun, setLiveRun] = useState<PactlineRun | null>(null);\n  const [apiError, setApiError] = useState("");');
source = source.replace('  const stateCopy = useMemo(() => {\n    if (runState === "approved") return { label: "Action approved", sub: "Run resumed · 14:33:01", tone: "green" };', '  useEffect(() => {\n    fetchRunState().then((data) => {\n      if (data.currentRun) { setLiveRun(data.currentRun); setRunState(data.currentRun.status === "held" ? "held" : data.currentRun.status); }\n    }).catch(() => setApiError("Live API is unavailable; showing the local proof state."));\n  }, []);\n\n  const stateCopy = useMemo(() => {\n    if (runState === "approved") return { label: "Action approved", sub: "Run resumed · live API", tone: "green" };\n    if (runState === "rejected") return { label: "Action rejected", sub: "Unauthorized action cancelled", tone: "muted" };');
source = source.replace('  const simulateRun = () => {\n    setRunState("running");\n    notify("Intent captured · agent run started");\n    window.setTimeout(() => setRunState("held"), 1300);\n  };\n\n  const approve = () => {\n    setRunState("approved");\n    setShowDrawer(false);\n    notify("Approved · agent resumed through ArmorIQ");\n  };\n\n  const reject = () => {\n    setRunState("idle");\n    setShowDrawer(false);\n    notify("Rejected · unauthorized action did not execute");\n  };', '  const simulateRun = async () => {\n    setRunState("running");\n    setApiError("");\n    notify("Intent captured · starting live run");\n    try {\n      const nextRun = await startPactlineRun();\n      setLiveRun(nextRun);\n      setRunState(nextRun.status);\n      setShowDrawer(true);\n    } catch {\n      setApiError("Live API unavailable; run not started.");\n      setRunState("held");\n      notify("Live API unavailable · local state unchanged");\n    }\n  };\n\n  const approve = async () => {\n    try { const nextRun = await submitPactlineDecision("approve"); setLiveRun(nextRun); setRunState("approved"); setShowDrawer(false); notify("Approved · run updated by API"); }\n    catch { setApiError("Approval could not be submitted."); }\n  };\n\n  const reject = async () => {\n    try { const nextRun = await submitPactlineDecision("reject"); setLiveRun(nextRun); setRunState("rejected"); setShowDrawer(false); notify("Rejected · unauthorized action did not execute"); }\n    catch { setApiError("Rejection could not be submitted."); }\n  };\n\n  const displayedToolCalls = liveRun?.actions || toolCalls;');
source = source.replace('{toolCalls.map((call, index) => <div className={`tool-row ${call.tone === "amber" ? "is-held" : ""}`} key={call.name}><div className="tool-index">0{index + 1}</div><div className="tool-main"><strong>{call.name}</strong><span>{call.target}</span></div><div className={`tool-result ${call.tone}`}><span className="result-dot" />{call.result}</div><div className="tool-latency">{call.latency}</div><ChevronRight size={15} className="tool-chevron" /></div>)}</div>', '{displayedToolCalls.map((call, index) => { const isHeld = "decision" in call ? call.decision === "held" : call.tone === "amber"; const result = "decision" in call ? call.decision : call.result.toLowerCase(); const tone = isHeld ? "amber" : result === "rejected" ? "muted" : "green"; return <div className={`tool-row ${isHeld ? "is-held" : ""}`} key={call.name}><div className="tool-index">0{index + 1}</div><div className="tool-main"><strong>{call.name}</strong><span>{call.target}</span></div><div className={`tool-result ${tone}`}><span className="result-dot" />{result}</div><div className="tool-latency">{call.latency}</div><ChevronRight size={15} className="tool-chevron" /></div>; })}</div>');
source = source.replace('<footer className="page-footer"><span>', '{apiError && <div className="api-status" role="status">{apiError}</div>}\n        <footer className="page-footer"><span>');
source = source.replace('<div className="status-code">run_7F3A9C</div>', '<div className="status-code">{liveRun?.runId || "run_pending"}</div>');
source = source.replace('<div className="hero-visual-meta"><span className="status-dot live" />Signed · verified · 14:32:07</div>', '<div className="hero-visual-meta"><span className="status-dot live" />{liveRun ? `${liveRun.plan.status} · ${liveRun.mode}` : "Connecting to Pactline API…"}</div>');
source = source.replace('<div className="intent-copy">Read invoice → normalize fields → write ledger record → notify approved recipient</div><div className="ribbon-proof"><BadgeCheck size={15} /><span>plan_2b90…8a1</span></div>', '<div className="intent-copy">{liveRun?.plan.steps.join(" → ") || "Read invoice → normalize fields → write ledger record → notify approved recipient"}</div><div className="ribbon-proof"><BadgeCheck size={15} /><span>{liveRun?.plan.id || "plan_pending"}</span></div>');
await writeFile(path, source);
